#!/bin/bash

target_ip="192.168.0.1"
target_port=80

for i in {1..100}; do
    payload=$(< /dev/urandom tr -dc 'a-zA-Z0-9' | head -c32)
    result=$(curl -s -o /dev/null -w "%{http_code}" "$target_ip":"$target_port"/"$payload")

    echo "Payload: $payload   Response: $result"
done
